=== folio-org/mod-marccat/ramls/schema/authority.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "canadianContentIndicator": {
      "type": "string"
    },
    "verificationLevel": {
      "type": "string"
    },
    "leader": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "code",
        "value"
      ]
    },
    "fields": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "fieldStatus": {
              "type": "string"
            },
            "fixedField": {
              "type": "object",
              "properties": {
                "categoryCode": {
                  "type": "integer"
                },
                "headerTypeCode": {
                  "type": "integer"
                },
                "code": {
                  "type": "string"
                },
                "displayValue": {
                  "type": "string"
                },
                "sequenceNumber": {
                  "type": "integer"
                },
                "attributes": {
                  "type": "object"
                }
              },
              "required": [
                "categoryCode",
                "headerTypeCode",
                "code",
                "displayValue",
                "sequenceNumber",
                "attributes"
              ]
            },
            "added": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "mandatory",
            "fieldStatus",
            "fixedField",
            "added"
          ]
        },
        {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "fieldStatus": {
              "type": "string"
            },
            "fixedField": {
              "type": "object",
              "properties": {
                "categoryCode": {
                  "type": "integer"
                },
                "description": {
                  "type": "string"
                },
                "headerTypeCode": {
                  "type": "integer"
                },
                "code": {
                  "type": "string"
                },
                "displayValue": {
                  "type": "string"
                },
                "sequenceNumber": {
                  "type": "integer"
                },
                "attributes": {
                  "type": "object"
                }
              },
              "required": [
                "categoryCode",
                "description",
                "headerTypeCode",
                "code",
                "displayValue",
                "sequenceNumber",
                "attributes"
              ]
            },
            "added": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "mandatory",
            "fieldStatus",
            "fixedField",
            "added"
          ]
        },
        {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "fieldStatus": {
              "type": "string"
            },
            "fixedField": {
              "type": "object",
              "properties": {
                "categoryCode": {
                  "type": "integer"
                },
                "headerTypeCode": {
                  "type": "integer"
                },
                "code": {
                  "type": "string"
                },
                "displayValue": {
                  "type": "string"
                },
                "sequenceNumber": {
                  "type": "integer"
                },
                "attributes": {
                  "type": "object"
                }
              },
              "required": [
                "categoryCode",
                "headerTypeCode",
                "code",
                "displayValue",
                "sequenceNumber",
                "attributes"
              ]
            },
            "added": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "mandatory",
            "fieldStatus",
            "fixedField",
            "added"
          ]
        },
        {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "fieldStatus": {
              "type": "string"
            },
            "variableField": {
              "type": "object",
              "properties": {
                "categoryCode": {
                  "type": "integer"
                },
                "ind1": {
                  "type": "string"
                },
                "ind2": {
                  "type": "string"
                },
                "code": {
                  "type": "string"
                },
                "displayValue": {
                  "type": "string"
                },
                "subfields": {
                  "type": "array",
                  "items": {}
                },
                "sequenceNumber": {
                  "type": "integer"
                },
                "skipInFiling": {
                  "type": "integer"
                }
              },
              "required": [
                "categoryCode",
                "ind1",
                "ind2",
                "code",
                "displayValue",
                "subfields",
                "sequenceNumber",
                "skipInFiling"
              ]
            },
            "added": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "mandatory",
            "fieldStatus",
            "variableField",
            "added"
          ]
        },
        {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "mandatory": {
              "type": "boolean"
            },
            "fieldStatus": {
              "type": "string"
            },
            "variableField": {
              "type": "object",
              "properties": {
                "keyNumber": {
                  "type": "integer"
                },
                "categoryCode": {
                  "type": "integer"
                },
                "headingTypeCode": {
                  "type": "string"
                },
                "itemTypeCode": {
                  "type": "string"
                },
                "functionCode": {
                  "type": "string"
                },
                "ind1": {
                  "type": "string"
                },
                "ind2": {
                  "type": "string"
                },
                "code": {
                  "type": "string"
                },
                "displayValue": {
                  "type": "string"
                },
                "subfields": {
                  "type": "array",
                  "items": {}
                },
                "sequenceNumber": {
                  "type": "integer"
                },
                "skipInFiling": {
                  "type": "integer"
                }
              },
              "required": [
                "keyNumber",
                "categoryCode",
                "headingTypeCode",
                "itemTypeCode",
                "functionCode",
                "ind1",
                "ind2",
                "code",
                "displayValue",
                "subfields",
                "sequenceNumber",
                "skipInFiling"
              ]
            },
            "added": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "mandatory",
            "fieldStatus",
            "variableField",
            "added"
          ]
        }
      ]
    },
    "recordView": {
      "type": "integer"
    }
  },
  "required": [
    "id",
    "canadianContentIndicator",
    "verificationLevel",
    "leader",
    "fields",
    "recordView"
  ]
}

=== folio-org/mod-marccat/src/test/resources/authority/name2.json
{
  "id": 0,
  "canadianContentIndicator": "0",
  "verificationLevel": "1",
  "leader": {
    "code": "000",
    "value": "00215nz   2200097n  4500"
  },
  "fields": [
    {
      "code": "001",
      "mandatory": true,
      "fieldStatus": "unchanged",
      "fixedField": {
        "categoryCode": 1,
        "headerTypeCode": 11,
        "code": "001",
        "displayValue": "00000000100",
        "sequenceNumber": 0,
        "attributes": {
          
        }
      },
      "added": true
    },
    {
      "code": "005",
      "mandatory": true,
      "fieldStatus": "unchanged",
      "fixedField": {
        "categoryCode": 1,
        "description": "005 Data/hour of transaction",
        "headerTypeCode": 41,
        "code": "005",
        "displayValue": "20200901111027.",
        "sequenceNumber": 0,
        "attributes": {
          
        }
      },
      "added": false
    },
    {
      "code": "008",
      "mandatory": true,
      "fieldStatus": "unchanged",
      "fixedField": {
        "categoryCode": 1,
        "headerTypeCode": 31,
        "code": "008",
        "displayValue": "200729 n annnnabbn n2ann und u",
        "sequenceNumber": 0,
        "attributes": {
          
        }
      },
      "added": true
    },
    {
      "code": "040",
      "mandatory": true,
      "fieldStatus": "unchanged",
      "variableField": {
        "categoryCode": 1,
        "ind1": " ",
        "ind2": " ",
        "code": "040",
        "displayValue": "\u001faSCA\u001fbeng",
        "subfields": [],
        "sequenceNumber": 0,
        "skipInFiling": 0
      },
      "added": true
    },
    {
      "code": "100",
      "mandatory": false,
      "fieldStatus": "new",
      "variableField": {
        "keyNumber": -1,
        "categoryCode": 2,
        "headingTypeCode": "1",
        "itemTypeCode": "2",
        "functionCode": "-1",
        "ind1": "1",
        "ind2": " ",
        "code": "100",
        "displayValue": "\u001faAlessandro Manzoni,\u001fd1785-1873.",
        "subfields": [],
        "sequenceNumber": 0,
        "skipInFiling": 0
      },
      "added": false
    }
  ],
  "recordView": 0
}

=== folio-org/mod-marccat/ramls/examples/subject.json
{
    "id":0,
    "canadianContentIndicator": "0",
    "verificationLevel": "1",
    "leader": {
      "code": "000",
      "value": "00215nz   2200097n  4500"
    },
    "fields": [
      {
        "code": "001",
        "mandatory": true,
        "fieldStatus": "unchanged",
        "fixedField": {
          "categoryCode": 1,
          "headerTypeCode": 11,
          "code": "001",
          "displayValue": "00000000100",
          "sequenceNumber": 0,
          "attributes": {}
        },
        "added": true
      },
      {
        "code": "005",
        "mandatory": true,
        "fieldStatus": "unchanged",
        "fixedField": {
          "categoryCode": 1,
          "description": "005 Data/hour of transaction",
          "headerTypeCode": 41,
          "code": "005",
          "displayValue": "20200901111027.",
          "sequenceNumber": 0,
          "attributes": {}
        },
        "added": false
      },
      {
        "code": "008",
        "mandatory": true,
        "fieldStatus": "unchanged",
        "fixedField": {
          "categoryCode": 1,
          "headerTypeCode": 31,
          "code": "008",
          "displayValue": "201001 n acanaaabn           n aaa     u",
          "sequenceNumber": 0,
          "attributes": {}
        },
        "added": true
      },
      {
        "code": "040",
        "mandatory": true,
        "fieldStatus": "unchanged",
        "variableField": {
          "categoryCode": 1,
          "ind1": " ",
          "ind2": " ",
          "code": "040",
          "displayValue": "\u001faSCA\u001fbeng",
          "subfields": [],
          "sequenceNumber": 0,
          "skipInFiling": 0
        },
        "added": true
      },
      {
        "code": "150",
        "mandatory": false,
        "fieldStatus": "new",
        "variableField": {
          "keyNumber": -1,
          "categoryCode": 4,
          "headingTypeCode": "1",
          "itemTypeCode": "2",
          "functionCode": "-1",
          "ind1": " ",
          "ind2": " ",
          "code": "150",
          "displayValue": "\u001faLa Historia de España",
          "subfields": [],
          "sequenceNumber": 0,
          "skipInFiling": 0
        },
        "added": false
      },
      {
        "code": "750",
        "mandatory": false,
        "fieldStatus": "new",
        "variableField": {
          "keyNumber": -1,
          "categoryCode": 4,
          "headingTypeCode": "1",
          "itemTypeCode": "2",
          "functionCode": "-1",
          "ind1": " ",
          "ind2": " ",
          "code": "750",
          "displayValue": "\u001faHistoria de España",
          "subfields": [],
          "sequenceNumber": 0,
          "skipInFiling": 0
        },
        "added": false
      },
      {
        "code": "670",
        "mandatory": false,
        "fieldStatus": "new",
        "variableField": {
          "keyNumber": -1,
          "categoryCode": 7,
          "headingTypeCode": "1",
          "itemTypeCode": "2",
          "functionCode": "-1",
          "ind1": " ",
          "ind2": " ",
          "code": "670",
          "displayValue": "\u001faHistoria",
          "subfields": [],
          "sequenceNumber": 0,
          "skipInFiling": 0
        },
        "added": false
      }
    ],
    "recordView": 0
}

=== folio-org/mod-marccat/ramls/examples/authorityTemplate.json
{
  "id": 362,
  "canadianContentIndicator": "0",
  "verificationLevel": "1",
  "leader": {
    "code": "000",
    "value": "00215nz   2200097n  4500"
  },
  "fields": [
    {
      "code": "001",
      "mandatory": true,
      "fieldStatus": "unchanged",
      "fixedField": {
        "keyNumber": 0,
        "categoryCode": 1,
        "headerTypeCode": 11,
        "code": "001",
        "displayValue": "00000000362",
        "sequenceNumber": 0,
        "attributes": {
          
        }
      },
      "added": false
    },
    {
      "code": "005",
      "mandatory": true,
      "fieldStatus": "unchanged",
      "fixedField": {
        "categoryCode": 1,
        "description": "046 Special Coded Dates",
        "headerTypeCode": 12,
        "code": "005",
        "displayValue": "20201026102004.",
        "sequenceNumber": 0,
        "attributes": {
          
        }
      },
      "added": false
    },
    {
      "code": "008",
      "mandatory": true,
      "fieldStatus": "unchanged",
      "fixedField": {
        "keyNumber": 0,
        "categoryCode": 1,
        "headerTypeCode": 10,
        "code": "008",
        "displayValue": "201026 n acanaaabn           n aaa     u",
        "dateEnteredOnFile": "201026",
        "sequenceNumber": 0,
        "attributes": {
          "dateEnteredOnFile": "201026"
        }
      },
      "added": false
    },
    {
      "code": "040",
      "mandatory": true,
      "fieldStatus": "unchanged",
      "variableField": {
        "keyNumber": 0,
        "categoryCode": 1,
        "headingTypeCode": "1",
        "itemTypeCode": "-1",
        "functionCode": "-1",
        "ind1": " ",
        "ind2": " ",
        "code": "040",
        "displayValue": "\u001faSCA\u001fbeng",
        "subfields": [],
        "sequenceNumber": 0,
        "skipInFiling": 0
      },
      "added": false
    }
  ],
  "recordView": 0
}
